# Generated by Django 4.1.5 on 2023-01-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSharpProgrammer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticTopCountCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, verbose_name='Регоин')),
                ('count', models.FloatField(verbose_name='Доля вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticTopSalaryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40, verbose_name='Регоин')),
                ('salary', models.FloatField(verbose_name='Средняя зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('middle_salary', models.IntegerField(verbose_name='Средняя зарплата')),
                ('count_vacancy', models.IntegerField(verbose_name='Количество вакансий')),
                ('middle_salary_profession', models.IntegerField(verbose_name='Средняя зарплата C# Программиста')),
                ('count_vacancy_profession', models.IntegerField(verbose_name='Колличество вакансий C# Программист')),
            ],
        ),
        migrations.CreateModel(
            name='TopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=80, verbose_name='Навык')),
                ('count', models.IntegerField(verbose_name='Встречается столько раз')),
            ],
        ),
    ]
